name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      APP_NAME: "desktop-icons.exe"

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils

      - name: Build
        shell: msys2 {0}
        run: |
          windres resources.rc -O coff -o resources.o
          g++ main.cpp resources.o -o ${{ env.APP_NAME }} -lshell32 -municode -mwindows

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ env.APP_NAME }}

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} ${{ env.APP_NAME }} --generate-notes
